-- DAME Tools Hub: roles and per-tool edit access (2026-10-01).
--
-- HOW TO UPGRADE A LIVE SITE
--   1. Re-run db/schema.sql in the Supabase SQL Editor (safe: keeps users, library, mappings).
--      It adds the role 'superuser', the table app_tool_editors, the column app_tools.editable,
--      rewrites the app_* / cm_* / dn_* functions with the new checks, marks Compliance Maker
--      and Datasheet Notes as editable, and promotes the oldest approved admin (the account
--      made by app_bootstrap_admin) to super user.
--   2. Check who became super user, and move it if needed:
--        select username, role, status from public.app_users where role <> 'user';
--        select public.app_set_superuser('your.username');     -- only if it picked the wrong account
--   3. Push the site files to GitHub.
--
-- ROLES
--   superuser  one account, the site owner: everything below, plus roles, deleting users,
--              and the Tools / Team tiles tabs.
--   admin      approve / reject / disable users, set their tile access and "Can edit" tools,
--              reset their passwords. Edits every tool's library and mapping. Cannot touch
--              admin accounts, roles, or the tool list.
--   user       runs the tools. "Can edit" (app_tool_editors) opens one tool's edit screen.
--
-- This file is only the summary; there is nothing to run here beyond step 1 and 2 above.
select username, role, status from public.app_users where role <> 'user' order by role desc, created_at;
